name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.OS }}
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest", "windows-latest", "macos-13", "macos-14"]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: "23"
    - name: Test
      run: ./mill __.test
    - name: Publish locally
      run: ./mill __.publishLocal # This ensures that javadoc generation succeeds in particular

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: "23"
    - name: Publish
      run: |
        ./mill -i mill.scalalib.SonatypeCentralPublishModule/ \
          --username "$MILL_SONATYPE_USERNAME" \
          --password "$MILL_SONATYPE_PASSWORD"
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY }}
        MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
